version: "3.9"
services:
  bird-mixit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit
    image: us-central1-docker.pkg.dev/birdclef-eda-f22/birdclef-eda-f22/bird-mixit:latest
    volumes:
      - ../data/raw/sound_separation/bird_mixit_model_checkpoints:/app/checkpoints
      - ../scripts:/app/scripts
      - ../data:/mnt/data
