version: "3.9"
services:
  birdnet:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit
    image: us-central1-docker.pkg.dev/birdclef-eda-f22/birdclef-eda-f22/bird-mixit:latest
